spring:
  config:
    import: >
      optional:file:.env[.properties],
      optional:file:../.env[.properties]

  mongodb:
    authentication-database: ${AUTHENTICATION_DATABASE}
    database: review
    host: ${MONGO_HOST}
    password: ${MONGO_PASSWORD} # Consider using a secure method in production!
    port: ${MONGO_PORT}
    username: ${MONGO_USERNAME}
    representation.uuid: standard

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop  # Not recommended for production!
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 300000
  refresh-token-expiration: 3600000