spring:
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB:admin}
      username: ${MONGO_USERNAME:rootuser}
      password: ${MONGO_PASSWORD:rootpass} # Consider using a secure method in production!
      port: ${MONGO_PORT:27017}
      database: review
      host: ${MONGO_HOST:localhost}
      uuid-representation: standard

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/start}
    username: ${DB_USERNAME:start-adm}
    password: ${DB_PASSWORD:start-doing-it}

  jpa:
    hibernate:
      ddl-auto: create-drop  # Not recommended for production!
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  key: ${JWT_KEY:dasdasdadadasdasdadadasdasdadadasdasdadadasdasdada}
  access-token-expiration: 300000
  refresh-token-expiration: 3600000