spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 300000
  refresh-token-expiration: 3600000