package br.all.domain.model.study

enum class StudyType {
    ARTICLE, BOOK, BOOKLET, COMMENT,
    INBOOK, INCOLLECTION, INPROCEEDINGS,
    MANUAL, MASTERSTHESIS, MISC,
    PHDTHESIS, PROCEEDINGS, TECHREPORT,
    UNPUBLISHED, UNKNOWN
}