package br.all.domain.model.study

enum class StudyTypes {
    ARTICLE, BOOK, BOOKLET,
    INBOOK, INCOLLECTION, INPROCEEDINGS,
    MANUAL, MASTERSTHESIS, MISC,
    PHDTHESIS, PROCEEDINGS, TECHREPORT,
    UNPUBLISHED, UNKNOWN
}